version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fusionpact-frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fusionpact-backend
    ports:
      - "8000:8000"
    restart: unless-stopped